fg_master:
    resource: "@FGMasterBundle/Resources/config/routing.yml"
    prefix:   /

fg_news:
    resource: "@FGNewsBundle/Resources/config/routing.yml"
    prefix:   /news/
login:
  path: /login
  defaults: 
      _controller: FGUserBundle:Security:login
login_check:
  path: /login_check
logout:
  path: /logout
