fg_news_homepage:
    path:     /{page}
    defaults:
      _controller: FGNewsBundle:News:index
      page: 1
    requirements:
      page: \d*
fg_news_view:
    path:     /view/{id}
    defaults:
      _controller: FGNewsBundle:News:view
    requirements:
      id: \d*
fg_news_add:
    path:     /add
    defaults:
      _controller: FGNewsBundle:News:add
fg_news_edit:
    path:     /edit/{id}
    defaults:
      _controller: FGNewsBundle:News:edit
    requirements:
      id: \d+
fg_news_delete:
    path:     /delete/{id}
    defaults:
      _controller: FGNewsBundle:News:delete
    requirements:
      id: \d+